on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-badges:
    name: Build badges
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node.js version 16.x
      - name: Install Node.js version 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Cache node modules
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-yarn
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install yarn
        run: npm i -g yarn

      # Download docs from cache
      - name: Download docs from cache
        uses: actions/cache@v2
        with:
          path: documentation
          key: ${{ runner.os }}-docs-build-${{ hashFiles('**/yarn.lock') }}

      # Download unit tests from cache
      - name: Download unit tests from cache
        uses: actions/cache@v2
        with:
          path: coverage
          key: ${{ runner.os }}-unit-tests-${{ hashFiles('**/yarn.lock') }}

      # Build badges
      - name: Badges build
        run: yarn badges:build

      # Cache results
      - name: Cache results
        uses: actions/cache@v2
        with:
          path: badges
          key: ${{ runner.os }}-badges-build-${{ hashFiles('**/yarn.lock') }}

