name: Development PR checks

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      MYSQL_PASSWORD:
        description: MySQL password
        required: true
      SPRING_APPLICATION_PROPERTIES:
        description: Spring application properties
        required: true
      VERNITE_2022_PRIVATE_KEY_PEM:
        description: Vernite 2022 private key PEM
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          mysql-password: ${{ secrets.MYSQL_PASSWORD }}
          spring-application-properties: ${{ secrets.SPRING_APPLICATION_PROPERTIES }}
          vernite-2022-private-key-pem: ${{ secrets.VERNITE_2022_PRIVATE_KEY_PEM }}

      - name: Build affected projects
        run: yarn nx affected --target=build
