name: Deploy client

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
        description: insiders or production
    secrets:
      SSH_KEY_FRONTEND:
        required: true
        description: SSH key for frontend server
      MYSQL_PASSWORD:
        description: MySQL password
        required: true
      SPRING_APPLICATION_PROPERTIES:
        description: Spring application properties
        required: true
      VERNITE_2022_PRIVATE_KEY_PEM:
        description: Vernite 2022 private key PEM
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/client

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          configuration: ${{ inputs.configuration }}
          mysql-password: ${{ secrets.MYSQL_PASSWORD }}
          spring-application-properties: ${{ secrets.SPRING_APPLICATION_PROPERTIES }}
          vernite-2022-private-key-pem: ${{ secrets.VERNITE_2022_PRIVATE_KEY_PEM }}

      # Deploy client using rsync
      - name: Deploy app 🚀
        uses: easingthemes/ssh-deploy@main
        if: ${{ contains(fromJSON(steps.affected.outputs.affected).projects, 'client') }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_FRONTEND }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./packages/client/dist/vernite/"
          REMOTE_HOST: '51.83.255.98'
          REMOTE_PORT: '2224'
          REMOTE_USER: 'frontend'
          TARGET: "/var/www/html/${{ inputs.configuration == 'insiders' && 'dev' || 'prod' }}"
          EXCLUDE: "/dist/, /node_modules/"
