name: Deploy docs to GitHub Pages

on:
  workflow_call:
    inputs:
      # Available options: dev, prod
      configuration:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Download cache (documentation)
      - name: Download cache (documentation)
        uses: actions/cache@v2
        with:
          path: documentation
          key: ${{ runner.os }}-docs-build-${{ hashFiles('**/yarn.lock') }}

      # Download cache (unit-tests)
      - name: Download cache (unit-tests)
        uses: actions/cache@v2
        with:
          path: coverage
          key: ${{ runner.os }}-unit-tests-${{ github.run_id }

      # Download cache (audit-report)
      - name: Download cache (audit-report)
        uses: actions/cache@v2
        with:
          path: documentation/audit
          key: ${{ runner.os }}-audit-build-${{ github.run_id }

      # Get app version from package.json
      - name: Get app version
        id: get_version
        run: >
          echo VERSION=$(CONFIGURATION=${{ inputs.configuration }} node -p -e "process.env.CONFIGURATION == 'dev' ? 'dev' : require('./package.json').version") >> $GITHUB_ENV

      # Deploy documentation to Github pages
      - name: Deploy documentation 📄
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: documentation
          target-folder: ${{ env.VERSION }}
          clean: false

      # Deploy documentation index to Github pages
      - name: Deploy docs-pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs-pages
          clean: false
