name: Build server docs and deploy to GitHub Pages

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
        description: vernite-dev or vernite
    secrets:
      MYSQL_PASSWORD:
        required: true
      SPRING_APPLICATION_PROPERTIES:
        required: true
      VERNITE_2022_PRIVATE_KEY_PEM:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/server

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          configuration: ${{ inputs.configuration }}
          mysql-password: ${{ secrets.MYSQL_PASSWORD }}
          spring-application-properties: ${{ secrets.SPRING_APPLICATION_PROPERTIES }}
          vernite-2022-private-key-pem: ${{ secrets.VERNITE_2022_PRIVATE_KEY_PEM }}

      # Build javadoc and jacoco
      - name: Generate Javadoc & Jacoco
        if: ${{ contains(fromJSON(steps.setup.outputs.affected-projects), 'server') }}
        run: mvn jacoco:report javadoc:javadoc

      # Upload code coverage
      - name: Generate code coverage
        if: ${{ contains(fromJSON(steps.setup.outputs.affected-projects), 'server') }}
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml

      # Deploy to GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ contains(fromJSON(steps.setup.outputs.affected-projects), 'server') }}
        with:
          branch: gh-pages
          folder: packages/server/target/site
          target-folder: server
          single-commit: true
