name: Build server docs and deploy to GitHub Pages

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      MYSQL_PASSWORD:
        required: true
      SPRING_APPLICATION_PROPERTIES:
        required: true
      VERNITE_2022_PRIVATE_KEY_PEM:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/server

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      # Install and configure MySQL
      - name: Install and configure MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -h 127.0.0.1 -uroot -proot -e 'create database vernite charset utf8mb4'
          mysql -h 127.0.0.1 -uroot -proot -e 'create database vernite_test charset utf8mb4'
          mysql -h 127.0.0.1 -uroot -proot -e 'create user "vernite"@"localhost" identified by "${{ secrets.MYSQL_PASSWORD }}"'
          mysql -h 127.0.0.1 -uroot -proot -e 'grant all on *.* to "vernite"@"localhost" with grant option'

      # Install properties secrets
      - name: Install properties
        run: 'echo "$SPRING_APPLICATION_PROPERTIES" > application.properties'
        env:
          SPRING_APPLICATION_PROPERTIES: ${{ secrets.SPRING_APPLICATION_PROPERTIES }}

      # Prepare secret for signing JWT
      - name: Prepare secret
        run: |
          echo "${{ secrets.VERNITE_2022_PRIVATE_KEY_PEM }}" > key.pem
          openssl pkcs8 -topk8 -inform pem -in key.pem -out "vernite-2022.private-key.der" -outform der -nocrypt

      # Download cache
      - name: Download cache
        uses: actions/cache@v3
        with:
          path: packages/server/target
          key: ${{ runner.os }}-${{ github.run_id }}-build-server

      # Build javadoc and jacoco
      - name: Generate Javadoc & Jacoco
        if: steps.cache.outputs.cache-hit == 'true'
        run: mvn jacoco:report javadoc:javadoc

      # Upload code coverage
      - name: Generate code coverage
        if: steps.cache.outputs.cache-hit == 'true'
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml

      # Deploy to GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: packages/server/target/site
          target-folder: server
          single-commit: true

      # Add result to summary
      - name: Add success result to summary
        if: steps.cache.outputs.cache-hit == 'true'
        run: echo "🟩 - Server docs build success" >> $GITHUB_STEP_SUMMARY

      - name: Add skipped result to summary
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "⬜ - Server docs build skipped" >> $GITHUB_STEP_SUMMARY
