on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Download cache
      - name: Download cache
        uses: actions/cache@v2
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-build-

      # Download artifacts (coverage)
      - name: Download artifacts (coverage)
        uses: actions/download-artifact@v2
        with:
          name: unit-tests
          path: coverage

      # SonarQube scan
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
