name: Development PR checks

on:
  workflow_call:

jobs:
  summary:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Collect client package details from logs
        uses: ./.github/actions/collect-client-package-details
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
