name: Development PR checks

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      MYSQL_PASSWORD:
        required: true
      SPRING_APPLICATION_PROPERTIES:
        required: true
      VERNITE_2022_PRIVATE_KEY_PEM:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # Install and configure MySQL
      - name: Install and configure MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -h 127.0.0.1 -uroot -proot -e 'create database vernite charset utf8mb4'
          mysql -h 127.0.0.1 -uroot -proot -e 'create database vernite_test charset utf8mb4'
          mysql -h 127.0.0.1 -uroot -proot -e 'create user "vernite"@"localhost" identified by "${{ secrets.MYSQL_PASSWORD }}"'
          mysql -h 127.0.0.1 -uroot -proot -e 'grant all on *.* to "vernite"@"localhost" with grant option'

      # Install properties secrets
      - name: Install properties
        run: 'echo "$SPRING_APPLICATION_PROPERTIES" > ./packages/server/application.properties'
        env:
          SPRING_APPLICATION_PROPERTIES: ${{ secrets.SPRING_APPLICATION_PROPERTIES }}

      # Prepare secret for signing JWT
      - name: Prepare secret
        run: |
          echo "${{ secrets.VERNITE_2022_PRIVATE_KEY_PEM }}" > key.pem
          openssl pkcs8 -topk8 -inform pem -in key.pem -out "./packages/server/vernite-2022.private-key.der" -outform der -nocrypt

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Test by nx
      - name: Test
        run:
          chmod +x packages/server/mvnw |
          yarn nx run-many --target=test

      # Cache results
      - name: Cache results
        uses: actions/cache@v3
        with:
          path: packages/server/target
          key: ${{ runner.os }}-build-${{ github.run_id }}
