name: Development PR checks

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      configuration:
        description: "The configuration to use (development | insiders | production)"
        required: true
        default: development
        type: string

    secrets:
      MYSQL_PASSWORD:
        description: MySQL password
        required: true
      SPRING_APPLICATION_PROPERTIES:
        description: Spring application properties
        required: true
      VERNITE_2022_PRIVATE_KEY_PEM:
        description: Vernite 2022 private key PEM
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          configuration: ${{ inputs.configuration }}
          mysql-password: ${{ secrets.MYSQL_PASSWORD }}
          spring-application-properties: ${{ secrets.SPRING_APPLICATION_PROPERTIES }}
          vernite-2022-private-key-pem: ${{ secrets.VERNITE_2022_PRIVATE_KEY_PEM }}

      # Test by nx
      - name: Test
        run: yarn nx affected --target=test
