on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-badges:
    name: Build badges
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node.js version 16.x
      - name: Install Node.js version 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Cache node modules
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-yarn
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install yarn
        run: npm i -g yarn

      # Download artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: documentation
          path: documentation

      # Download artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: unit-tests
          path: coverage/vernite

      # Build badges
      - name: Badges build
        run: yarn badges:build

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: badges
          path: badges

