name: Dev checks

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:
  workflow_call:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  prepare-environment:
    uses: vernite/frontend/.github/workflows/prepare-environment.yml

  unit-tests:
    needs: prepare-environment
    uses: vernite/frontend/.github/workflows/unit-tests.yml

  e2e-tests:
    needs: prepare-environment
    uses: vernite/frontend/.github/workflows/e2e-tests.yml
