name: Insiders server deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      configuration: insiders

  test:
    uses: ./.github/workflows/_test.yml
    needs: [build]
    secrets: inherit
    with:
      configuration: insiders

  deploy_client:
    needs: [build, test]
    uses: ./.github/workflows/_client-deploy.yml
    secrets: inherit
    with:
      configuration: insiders

  deploy_server:
    needs: [build, test]
    uses: ./.github/workflows/_server-deploy.yml
    secrets: inherit
    with:
      configuration: insiders

  sonar_server:
    needs: [build, test]
    uses: ./.github/workflows/_server-sonar.yml
    secrets: inherit
    with:
      configuration: insiders

  docs_server:
    needs: [build]
    uses: ./.github/workflows/_server-docs.yml
    secrets: inherit
    with:
      configuration: insiders

  publish_code_coverage:
    needs: [build, test]
    uses: ./.github/workflows/_publish-code-coverage.yml
    secrets: inherit
