name: Development PR checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      cache: ${{ github.run_id }}
    secrets: inherit

  test:
    uses: ./.github/workflows/_test.yml
    secrets: inherit

  affected:
    runs-on: ubuntu-latest
    steps:
      - name: Generate affected
        id: affected
        run: echo -e "affected=$(yarn -s nx print-affected | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Print
        run: echo -e "affected=$(yarn -s nx print-affected | tr -d '\n')"

      - name: Print
        run: echo ${{ steps.affected.outputs.affected }}

      - name: Print projects
        run: echo ${{ fromJSON(steps.affected.outputs.affected).projects }}
