name: Dev checks

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:
  workflow_call:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  prepare-environment:
    needs: [checkout]
    name: Prepare environment
    uses: ./.github/workflows/prepare-environment.yml

  unit-tests:
    needs: [prepare-environment]
    name: Unit tests
    uses: ./.github/workflows/unit-tests.yml

  e2e-tests:
    needs: [prepare-environment]
    name: E2E tests
    uses: ./.github/workflows/e2e-tests.yml

  deploy:
    needs: [unit-tests]
    name: Deploy to vernite server
    uses: ./.github/workflows/deploy.yml
    with:
      directory: dev
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
