name: Insiders server deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/_test.yml
    secrets: inherit

  deploy_client:
    needs: [build, test]
    uses: ./.github/workflows/_client-deploy.yml
    with:
      configuration: insiders
    secrets: inherit

  deploy_server:
    needs: [build, test]
    uses: ./.github/workflows/_server-deploy.yml
    with:
      configuration: vernite-dev
    secrets: inherit

  sonar_server:
    needs: [build]
    uses: ./.github/workflows/_server-sonar.yml
    secrets: inherit

  docs_server:
    needs: [build]
    uses: ./.github/workflows/_server-docs.yml
    secrets: inherit
