name: Development PR checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/_test.yml
    secrets: inherit
