name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install and configure MySQL
      run: |
        sudo systemctl start mysql.service
        mysql -h 127.0.0.1 -uroot -proot -e 'create database workflow charset utf8mb4'
        mysql -h 127.0.0.1 -uroot -proot -e 'create database workflow_test charset utf8mb4'
        mysql -h 127.0.0.1 -uroot -proot -e 'create user "workflow"@"localhost" identified by "${{ secrets.MYSQL_PASSWORD }}"'
        mysql -h 127.0.0.1 -uroot -proot -e 'grant all on *.* to "workflow"@"localhost" with grant option'
    - name: Install properties
      run: 'echo "$SPRING_APPLICATION_PROPERTIES" > application.properties'
      env:
        SPRING_APPLICATION_PROPERTIES: ${{ secrets.SPRING_APPLICATION_PROPERTIES }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate code coverage
      run: mvn test
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: target/site/jacoco/jacoco.xml
    - name: Prepare SSH
      run: |
        eval $(ssh-agent -s)
        echo "${{ secrets.AUTO_DEPLOY_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -t rsa -p 2224 51.77.50.209 >> ~/.ssh/known_hosts
        rsync -a -e 'ssh -p 2224' target/workflow*jar backend@51.77.50.209:~/workflow.jar
        ssh -p 2224 backend@51.77.50.209 "sudo /usr/bin/systemctl restart workflow.service"
