name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install and configure MySQL
      run: |
        sudo service mysql start
        mysql -h 127.0.0.1 -uroot -proot -e 'create database workflow charset utf8mb4'
        mysql -h 127.0.0.1 -uroot -proot -e 'create user "workflow"@"localhost" identified by "IBvmFN4LvHHVfzKRyGYRCQBKadMRyuIu7B5XL0AZ"'
        mysql -h 127.0.0.1 -uroot -proot -e 'grant all on *.* to "workflow"@"localhost" with grant option'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
