name: TypeScript
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Build proto libraries ⚙️
        run: |
          protoc -I=./proto --java_out="dist/java" proto/vernite.proto
      - name: Create dependency
        run: mvn install
