name: Production server deploy

on:
  workflow_dispatch:
  push:
    branches:
      - stable

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      configuration: production

  test:
    uses: ./.github/workflows/_test.yml
    secrets: inherit

  deploy_client:
    needs: [build, test]
    uses: ./.github/workflows/_client-deploy.yml
    secrets: inherit
    with:
      configuration: production

  deploy_server:
    needs: [build, test]
    uses: ./.github/workflows/_server-deploy.yml
    secrets: inherit
    with:
      configuration: vernite
