name: Production server deploy

on:
  workflow_dispatch:
  push:
    branches:
      - stable

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/_test.yml
    secrets: inherit

  # TODO: Uncomment when client is ready
  # deploy_client:
  #   needs: [build, test]
  #   uses: ./.github/workflows/_client-deploy.yml
  #   with:
  #     configuration: insiders
  #   secrets: inherit

  deploy_server:
    needs: [build, test]
    uses: ./.github/workflows/_server-deploy.yml
    with:
      configuration: vernite
    secrets: inherit
