name: Server dependency review

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'packages/server/pom.xml'
    

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v1
