name: Production server checks

on:
  push:
    branches:
      - main
    paths:
      - 'packages/server/**'

jobs:
  build:
    uses: ./.github/workflows/server-build.yml

  deploy:
    needs: [build]
    uses: ./.github/workflows/server-deploy.yml
    with:
      config: vernite
    secrets:
      AUTO_DEPLOY_KEY: ${{ secrets.AUTO_DEPLOY_KEY }}
