name: Development server checks

on:
  push:
    branches:
      - dev
    paths:
      - 'packages/server/**'
jobs:
  build:
    uses: ./.github/workflows/server-build.yml
    secrets:
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      SPRING_APPLICATION_PROPERTIES: ${{ secrets.SPRING_APPLICATION_PROPERTIES }}
      VERNITE_2022_PRIVATE_KEY_PEM: ${{ secrets.VERNITE_2022_PRIVATE_KEY_PEM }}

  deploy:
    needs: [build]
    uses: ./.github/workflows/server-deploy.yml
    with:
      config: vernite-dev
    secrets:
      AUTO_DEPLOY_KEY: ${{ secrets.AUTO_DEPLOY_KEY }}

  sonar:
    needs: [build]
    uses: ./.github/workflows/server-sonar.yml
    secrets:
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      SPRING_APPLICATION_PROPERTIES: ${{ secrets.SPRING_APPLICATION_PROPERTIES }}
      VERNITE_2022_PRIVATE_KEY_PEM: ${{ secrets.VERNITE_2022_PRIVATE_KEY_PEM }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  docs:
    needs: [build]
    uses: ./.github/workflows/server-docs.yml
    secrets:
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      SPRING_APPLICATION_PROPERTIES: ${{ secrets.SPRING_APPLICATION_PROPERTIES }}
      VERNITE_2022_PRIVATE_KEY_PEM: ${{ secrets.VERNITE_2022_PRIVATE_KEY_PEM }}
