name: Unit Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Download artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: environment

      # Run unit tests
      - name: Unit tests
        run: yarn unit:build

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests
          path: coverage/vernite

