name: Version bump
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target version'
        required: true
        type: string

permissions:
  contents: write

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        id: setup
        uses: ./.github/actions/setup
        with:
          configuration: production
          mysql-password: ${{ secrets.MYSQL_PASSWORD }}
          spring-application-properties: ${{ secrets.SPRING_APPLICATION_PROPERTIES }}
          vernite-2022-private-key-pem: ${{ secrets.VERNITE_2022_PRIVATE_KEY_PEM }}

      - name: Bump versions
        run: |
          node packages/tools/version-all.js --version=${{ inputs.version }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Bump version to ${{ inputs.version }}"
          tag: ${{ inputs.version }}

  build:
    needs: [version-bump]
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      configuration: production
      all: true

  test:
    needs: [version-bump]
    uses: ./.github/workflows/_test.yml
    secrets: inherit
    with:
      configuration: production

  deploy_client:
    needs: [build, test]
    uses: ./.github/workflows/_client-deploy.yml
    secrets: inherit
    with:
      configuration: production

  deploy_server:
    needs: [build, test]
    uses: ./.github/workflows/_server-deploy.yml
    secrets: inherit
    with:
      configuration: production

  upload_artifacts:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Restore all projects caches
        uses: ./.github/actions/restore-projects-cache
        with:
          configuration: production

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          append_body: true
          tag_name: ${{ inputs.version }}
          files: |
            packages/server/target/*.jar
            packages/client/dist/**
