name: Version bump
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target version'
        required: true
        type: string

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}

      - name: Setup environment
        id: setup
        uses: ./.github/actions/setup
        with:
          configuration: production
          mysql-password: ${{ secrets.MYSQL_PASSWORD }}
          spring-application-properties: ${{ secrets.SPRING_APPLICATION_PROPERTIES }}
          vernite-2022-private-key-pem: ${{ secrets.VERNITE_2022_PRIVATE_KEY_PEM }}

      - name: Bump versions
        run: |
          node packages/tools/version-all.js --version=${{ inputs.version }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Bump version to ${{ inputs.version }}"
          tag: ${{ inputs.version }}
          committer_name: vernite-bot
          committer_email: contact.vernite@gmail.com
          author_name: vernite-bot
          author_email: contact.vernite@gmail.com
